server:
  port: 9001

spring:
  h2:
    console:
      enabled: true
  application:
    name: DEPARTMENT-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
    instance:
      hostname: localhost